#!/bin/bash

gcc -o mdlj mdlj.c -lm -lgsl  -lgslcblas -lm

N=64
T=0.44
rho=0.5

echo "rx ry rz vx vy vz" > data1
echo "rx ry rz vx vy vz" > data2
./mdlj -N $N -rho $rho -T0 $T -T $T -uf -dt 0.001 -ns 10000 -fs 100 >> data1
./mdlj -N $N -rho $rho -T0 $T -T $T -uf -dt 0.0001 -ns 100000 -fs 1000 >> data2

python tm.py
